# Generated by Django 5.2.16 on 2026-07-17 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tei', models.CharField(max_length=20, unique=True)),
                ('seriennummer', models.CharField(max_length=50, unique=True)),
                ('geraetename', models.CharField(max_length=100)),
                ('issi', models.CharField(max_length=20, unique=True)),
                ('status', models.CharField(choices=[('betrieb', 'In Betrieb'), ('reparatur', 'In Reparatur'), ('archiv', 'Ausgemustert')], default='betrieb', max_length=20)),
            ],
        ),
    ]
