# Generated by Django 5.2.16 on 2026-07-21 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_device_softwareversion_alter_device_geraetename_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='softwareversion',
            new_name='bos_sika_nummer',
        ),
        migrations.AddField(
            model_name='device',
            name='bos_sika_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='device',
            name='eigentuemer',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='device',
            name='funkrufname',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='device',
            name='kommune',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='device',
            name='landkreis',
            field=models.CharField(blank=True, default='', max_length=5),
        ),
        migrations.AddField(
            model_name='device',
            name='nutzer',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='device',
            name='organisationsart',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='device',
            name='organisationsname',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='device',
            name='software_version',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='device',
            name='verwaltungsgemeinschaft',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='device',
            name='verwendung',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
