# Generated by Django 6.0.7 on 2026-07-28 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0004_device_assigned_to_device_needs_programming_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='needs_programming',
        ),
    ]
