# Generated by Django 6.0.7 on 2026-07-28 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0005_remove_device_needs_programming'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='programming_status',
        ),
    ]
