# Generated by Django 5.2.16 on 2026-08-04 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0006_remove_device_programming_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='bemerkung',
            field=models.TextField(blank=True, default=''),
        ),
    ]
