# Generated by Django 5.2.16 on 2026-08-13 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0007_device_bemerkung'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('import_type', models.CharField(max_length=50, unique=True)),
                ('last_import', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
