# Generated by Django 5.2.16 on 2026-09-03 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0008_importstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='eg_art',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='device',
            name='eg_typ',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='device',
            name='hersteller',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
