# Generated by Django 5.2.16 on 2026-09-03 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0009_device_eg_art_device_eg_typ_device_hersteller'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='fahrzeugart',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
