# Generated by Django 5.2.16 on 2026-09-03 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0010_device_fahrzeugart'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='datum_ttb',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
