# Generated by Django 5.2.16 on 2026-09-04 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0012_device_aopta_aa_device_aopta_ab_device_aopta_ac_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='heimat_dienststelle',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
