# Generated by Django 5.2.16 on 2026-09-04 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0013_device_heimat_dienststelle'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='dienststelle',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
