# Generated by Django 5.2.16 on 2026-09-10 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0014_device_dienststelle'),
    ]

    operations = [
        migrations.CreateModel(
            name='PagerReparatur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('begonnen_am', models.DateTimeField(auto_now_add=True)),
                ('zurueck_am', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('offen', 'Offen'), ('abgeschlossen', 'Abgeschlossen')], default='offen', max_length=20)),
                ('symptome', models.JSONField(blank=True, default=list)),
                ('reparaturart', models.JSONField(blank=True, default=list)),
                ('zubehoer', models.JSONField(blank=True, default=list)),
                ('plombennummern', models.TextField(blank=True, default='')),
                ('defektbeschreibung', models.TextField(blank=True, default='')),
                ('bemerkung', models.TextField(blank=True, default='')),
                ('pager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reparaturen', to='devices.device')),
            ],
        ),
    ]
