# Generated by Django 5.2.16 on 2026-09-10 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0015_pagerreparatur'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagerreparatur',
            name='artikel_modellnummer',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='pagerreparatur',
            name='option_features',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='pagerreparatur',
            name='rechnungsadresse',
            field=models.TextField(blank=True, default=''),
        ),
    ]
