# Generated by Django 5.2.16 on 2026-09-14 12:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0016_pagerreparatur_artikel_modellnummer_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Historie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zeitpunkt', models.DateTimeField(auto_now_add=True)),
                ('ereignis', models.CharField(max_length=100)),
                ('details', models.TextField(blank=True, default='')),
                ('benutzer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('geraet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historie', to='devices.device')),
            ],
        ),
    ]
