# Generated by Django 5.2.16 on 2026-09-15 13:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0017_historie'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Checkliste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('erstellt_am', models.DateTimeField(auto_now_add=True)),
                ('abgeschlossen_am', models.DateTimeField(blank=True, null=True)),
                ('geraet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='checkliste', to='devices.device')),
            ],
        ),
        migrations.CreateModel(
            name='Checklistenpunkt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('bezeichnung', models.CharField(max_length=255)),
                ('erledigt', models.BooleanField(default=False)),
                ('erforderlich', models.BooleanField(default=True)),
                ('erledigt_am', models.DateTimeField(blank=True, null=True)),
                ('checkliste', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='punkte', to='devices.checkliste')),
                ('erledigt_von', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='erledigte_checklistenpunkte', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
