# Generated by Django 5.2.16 on 2026-09-15 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0018_checkliste_checklistenpunkt'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkliste',
            name='import_am',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='checkliste',
            name='geraet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklisten', to='devices.device'),
        ),
    ]
