# Generated by Django 5.2.16 on 2026-09-16 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0019_checkliste_import_am_alter_checkliste_geraet'),
    ]

    operations = [
        migrations.CreateModel(
            name='SirenStammdaten',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gemeinde', models.CharField(blank=True, default='', max_length=100)),
                ('ortsteil', models.CharField(blank=True, default='', max_length=100)),
                ('standort_adresse', models.CharField(blank=True, default='', max_length=255)),
                ('laufende_nummer', models.CharField(blank=True, default='', max_length=50)),
                ('feueralarm', models.CharField(blank=True, default='', max_length=50)),
                ('warnung', models.CharField(blank=True, default='', max_length=50)),
                ('sirenenprobe', models.CharField(blank=True, default='', max_length=50)),
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='siren_stammdaten', to='devices.device')),
            ],
        ),
    ]
