# Generated by Django 5.2.16 on 2026-09-16 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0020_sirenstammdaten'),
    ]

    operations = [
        migrations.CreateModel(
            name='SirenFRTStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('beantragt', 'Beantragt'), ('freigegeben', 'Freigegeben'), ('fertig', 'Fertig')], default='beantragt', max_length=20)),
                ('antragsdatum', models.DateTimeField(blank=True, null=True)),
                ('freigabedatum', models.DateTimeField(blank=True, null=True)),
                ('fertigmeldedatum', models.DateTimeField(blank=True, null=True)),
                ('suchkreisname', models.CharField(blank=True, default='', max_length=150)),
                ('as_kommentar', models.TextField(blank=True, default='')),
                ('bemerkung_ttb', models.TextField(blank=True, default='')),
                ('sirene', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='frt_status', to='devices.sirenstammdaten')),
            ],
        ),
    ]
