# Generated by Django 5.2.16 on 2026-09-16 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0021_sirenfrtstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='sirenstammdaten',
            name='breitengrad',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='sirenstammdaten',
            name='laengengrad',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
    ]
