# Generated by Django 5.2.16 on 2026-09-23 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0022_sirenstammdaten_breitengrad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sirenfrtstatus',
            name='zuteilungsnummer',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
