# Generated by Django 5.2.16 on 2026-10-06 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0023_sirenfrtstatus_zuteilungsnummer'),
    ]

    operations = [
        migrations.AddField(
            model_name='sirenstammdaten',
            name='issi',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
