# Generated by Django 5.2.16 on 2026-09-16 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SirenFRTAntrag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suchkreisname', models.CharField(blank=True, default='', max_length=150)),
                ('ort', models.CharField(blank=True, default='', max_length=100)),
                ('plz', models.CharField(blank=True, default='', max_length=10)),
                ('strasse', models.CharField(blank=True, default='', max_length=150)),
                ('hausnummer', models.CharField(blank=True, default='', max_length=20)),
                ('breitengrad_grad', models.IntegerField(blank=True, null=True)),
                ('breitengrad_min', models.IntegerField(blank=True, null=True)),
                ('breitengrad_sek', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('laengengrad_grad', models.IntegerField(blank=True, null=True)),
                ('laengengrad_min', models.IntegerField(blank=True, null=True)),
                ('laengengrad_sek', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('standorthoehe', models.CharField(blank=True, default='', max_length=20)),
                ('antragsdatum', models.DateTimeField(blank=True, null=True)),
                ('erstellt_am', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
