# Generated by Django 5.2.16 on 2026-09-22 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alarmierung', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SirenFRTFreigabePending',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suchkreisname', models.CharField(blank=True, default='', max_length=150)),
                ('freigabedatum', models.DateTimeField(blank=True, null=True)),
                ('as_kommentar', models.TextField(blank=True, default='')),
                ('zuteilungsnummer', models.CharField(blank=True, default='', max_length=150)),
                ('erstellt_am', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
