# Generated by Django 5.2.16 on 2026-09-23 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alarmierung', '0002_sirenfrtfreigabepending'),
    ]

    operations = [
        migrations.AddField(
            model_name='sirenfrtantrag',
            name='hersteller',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
